services:
  db:
    image: postgres:16
    container_name: invento-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - invento-network

  redis:
    image: redis:alpine
    container_name: invento-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - invento-network

  maildev:
    image: maildev/maildev
    container_name: invento-maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - invento-network

  api:
    container_name: invento-api
    image: omaremad24/invento-api:latest
    build:
      context: .
      dockerfile: Presentation/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      maildev:
        condition: service_started
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - EmailSettings__Host=maildev
      - EmailSettings__Port=1025
      - EmailSettings__Username=""
      - EmailSettings__Password=""
    networks:
      - invento-network

  frontend:
    container_name: invento-frontend
    image: omaremad24/invento-frontend:latest
    build:
      context: ./Front
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api
    networks:
      - invento-network

volumes:
  postgres_data:

networks:
  invento-network:
    driver: bridge
